"""Where the skill's data lives.

The skill is the shipped artifact: copy `rules-report/` anywhere an agent can
run it and answering works offline, immediately, with no build step. Everything
needed for that is vendored in `data/`:

    data/rules.json    the parsed rulebook — 3,300+ addressable rules
    data/cards.json    every card's printed text, keywords and artwork URL
    data/rules.html    the anchored rulebook reports link into

Only *rebuilding* that data needs anything external, and only a maintainer does
that (`npm run oracle skill-data` in the source repo). `source_corpus_dir()`
below exists for exactly that path and is never touched while answering — a
user who never clones the repo should never see it mentioned.
"""
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.normpath(os.path.join(HERE, ".."))
DATA = os.path.join(SKILL, "data")
REPO = os.path.normpath(os.path.join(SKILL, "..", "..", ".."))

# Markdown the *rebuild* path reads. Not needed to answer a question.
REQUIRED_SOURCE = ("core-rules.md", "tournament-rules.md")


def data_path(name):
    """A file inside the skill's vendored data directory."""
    return os.path.join(DATA, name)


def _require(name, how):
    path = data_path(name)
    if not os.path.exists(path):
        raise SystemExit(
            f"Missing {name}.\n"
            f"  Expected at: {path}\n\n"
            f"  {how}"
        )
    return path


def rules_json():
    return _require(
        "rules.json",
        "This ships with the skill, so an absent copy means the install is\n"
        "  incomplete — re-copy the rules-report/ folder. To rebuild from source:\n"
        "    python3 rules_cli.py build",
    )


def cards_json():
    return _require(
        "cards.json",
        "This ships with the skill. Re-copy the rules-report/ folder, or\n"
        "  regenerate it from the source repo with:\n"
        "    npm run oracle skill-data",
    )


def load_cards():
    """name -> {name, text, keywords, image}. Empty dict if absent.

    Card lookup degrades to "no card matching X" rather than exploding, because
    a rules-only question is still answerable without card data.
    """
    try:
        with open(data_path("cards.json"), encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return {}


def rulebook_html_path():
    """The anchored rulebook. Generated by `rules_cli.py rulebook`."""
    return data_path("rules.html")


def reports_dir():
    path = os.path.join(SKILL, "reports")
    os.makedirs(path, exist_ok=True)
    return path


def source_corpus_dir():
    """Maintainer-only: the markdown `rules_cli.py build` parses.

    Resolution order, first usable wins: an explicit override, the source
    repo's output/, then an Obsidian vault raw/ folder if one is synced.
    """
    for candidate in (
        os.environ.get("RIFTBOUND_CORPUS"),
        os.path.join(REPO, "output"),
        os.environ.get("VAULT_RAW_DIR"),
    ):
        if candidate and all(
            os.path.exists(os.path.join(candidate, f)) for f in REQUIRED_SOURCE
        ):
            return candidate
    raise SystemExit(
        "No source corpus found — this is only needed to REBUILD the rulebook.\n"
        "  Answering questions uses the vendored data/rules.json and needs none of this.\n\n"
        f"  Looked for {', '.join(REQUIRED_SOURCE)} in:\n"
        f"    $RIFTBOUND_CORPUS   ({os.environ.get('RIFTBOUND_CORPUS') or 'unset'})\n"
        f"    {os.path.join(REPO, 'output')}\n"
        f"    $VAULT_RAW_DIR      ({os.environ.get('VAULT_RAW_DIR') or 'unset'})\n\n"
        "  Generate one from the source repo with:  npm run oracle process && npm run oracle extract"
    )


def source_card_files():
    """Maintainer-only: the per-set markdown that `oracle skill-data` folds into cards.json."""
    return sorted(glob.glob(os.path.join(source_corpus_dir(), "cards-*.md")))
